
FROM python:3.14-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc 

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

COPY . .

ENV DJANGO_SECRET="dummy_build_key_just_for_collectstatic"

RUN python manage.py collectstatic --noinput

EXPOSE 8000

CMD ["gunicorn", "monitor.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
