services:
  backend:
    build: ./mproj
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./mproj:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/hostname:/etc/hostname:ro
      - /run/udev:/run/udev:ro
      - /dev/disk:/dev/disk:ro
      - /run/udev:/run/udev:ro
      - /sys:/sys:ro
      - /:/host:ro
    pid: "host"
    environment:
      - HOST_NAME=${HOST_NAME}
    env_file:
      - .env

  celery_worker:
    build: ./mproj
    command: celery -A monitor worker -l info
    environment:
      - PROCFS_PATH=/host/proc
    volumes:
      - ./mproj:/app
      - /etc/localtime:/etc/localtime:ro
      - /run/udev:/run/udev:ro
      - /dev/disk:/dev/disk:ro
      - /run/udev:/run/udev:ro
      - /:/host:ro
      - /sys:/sys:ro
    privileged: true
    env_file:
      - .env
    pid: "host"
    depends_on:
      - rabbitmq

  celery_beat:
    build: ./mproj
    command: celery -A monitor beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./mproj:/app:z
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "15672:15672"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
