# Generated by Django 6.0.2 on 2026-02-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdata',
            name='avg_load',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
    ]
