# Generated by Django 6.0.2 on 2026-02-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0002_systemdata_avg_load'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('avg_load', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('free', models.DecimalField(decimal_places=0, max_digits=100)),
                ('total', models.DecimalField(decimal_places=0, max_digits=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SystemData',
        ),
    ]
