# Generated by Django 6.0.2 on 2026-02-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0003_cpudata_memorydata_delete_systemdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuUsageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cpu_usage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cpu_number', models.IntegerField()),
            ],
        ),
    ]
