# Generated by Django 6.0.2 on 2026-02-27 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0004_cpuusagedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpuusagedata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='cpuusagedata',
            name='cpu_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sysmon.cpudata'),
            preserve_default=False,
        ),
    ]
