# Generated by Django 6.0.2 on 2026-03-02 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0005_remove_cpuusagedata_timestamp_cpuusagedata_cpu_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_id', models.CharField()),
                ('hw_id_type', models.CharField()),
                ('device', models.CharField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='cpuusagedata',
            name='cpu_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_usage', to='sysmon.cpudata'),
        ),
        migrations.CreateModel(
            name='DiskUsageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=0, max_digits=100)),
                ('read_count', models.DecimalField(decimal_places=0, max_digits=100)),
                ('write_count', models.DecimalField(decimal_places=0, max_digits=100)),
                ('read_bytes', models.DecimalField(decimal_places=0, max_digits=100)),
                ('write_bytes', models.DecimalField(decimal_places=0, max_digits=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_usage', to='sysmon.diskdata')),
            ],
        ),
        migrations.CreateModel(
            name='PartitionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount_point', models.CharField()),
                ('filesystem', models.CharField()),
                ('uuid', models.CharField()),
                ('active', models.BooleanField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partition_data', to='sysmon.diskdata')),
            ],
        ),
        migrations.CreateModel(
            name='PartitionUsageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=0, max_digits=100)),
                ('free', models.DecimalField(decimal_places=0, max_digits=100)),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partition_usage', to='sysmon.partitiondata')),
            ],
        ),
    ]
