# Generated by Django 6.0.2 on 2026-03-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0006_diskdata_alter_cpuusagedata_cpu_data_diskusagedata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskdata',
            name='hw_id',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='diskusagedata',
            name='read_bytes',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='diskusagedata',
            name='read_count',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='diskusagedata',
            name='total',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='diskusagedata',
            name='write_bytes',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='diskusagedata',
            name='write_count',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='partitiondata',
            name='uuid',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='partitionusagedata',
            name='free',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='partitionusagedata',
            name='total',
            field=models.PositiveBigIntegerField(),
        ),
    ]
