# Generated by Django 6.0.2 on 2026-03-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0007_alter_diskdata_hw_id_alter_diskusagedata_read_bytes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitiondata',
            name='filesystem',
            field=models.CharField(null=True),
        ),
    ]
