# Generated by Django 6.0.2 on 2026-03-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0008_alter_partitiondata_filesystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitiondata',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
