# Generated by Django 6.0.2 on 2026-03-16 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0009_partitiondata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitiondata',
            name='filesystem',
        ),
        migrations.RemoveField(
            model_name='partitiondata',
            name='mount_point',
        ),
        migrations.CreateModel(
            name='FilesystemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(null=True)),
                ('mount_point', models.CharField()),
                ('uuid', models.CharField(unique=True)),
                ('active', models.BooleanField()),
                ('filesystem_type', models.CharField()),
                ('disk', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filesystem_data', to='sysmon.diskdata')),
                ('partition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filesystem_data', to='sysmon.partitiondata')),
            ],
        ),
        migrations.CreateModel(
            name='FilesystemUsageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('size', models.BigIntegerField()),
                ('free', models.PositiveBigIntegerField()),
                ('filesystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filesystem_usage', to='sysmon.filesystemdata')),
            ],
        ),
    ]
