# Generated by Django 6.0.2 on 2026-03-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0010_remove_partitiondata_filesystem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitiondata',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PartitionUsageData',
        ),
    ]
