# Generated by Django 6.0.2 on 2026-03-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0011_partitiondata_total_delete_partitionusagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskdata',
            name='type',
            field=models.CharField(default=False),
            preserve_default=False,
        ),
    ]
