# Generated by Django 6.0.2 on 2026-03-23 20:47

from django.db import migrations

def create_periodic_tasks(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=10,
        period='seconds',
    )

    PeriodicTask.objects.update_or_create(
        name='System polling',
        defaults={
            'task':'sysmon.tasks.check_memory_and_cpu',
            "interval":schedule,
        }
    )
    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=60 * 60 * 24,
        period='seconds',
    )

    PeriodicTask.objects.update_or_create(
        name='Database cleanup',
        defaults={
            'task':'sysmon.tasks.database_cleanup',
            "interval":schedule,
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0012_diskdata_type'),
        ('django_celery_beat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_periodic_tasks, reverse_code=migrations.RunPython.noop)
    ]
