# Generated by Django 6.0.2 on 2026-03-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0013_auto_20260323_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_period', models.DurationField(null=True)),
            ],
        ),
    ]
