# Generated by Django 6.0.2 on 2026-03-25 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmon', '0014_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystemdata',
            name='disk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filesystem_data', to='sysmon.diskdata'),
        ),
        migrations.AlterField(
            model_name='filesystemdata',
            name='partition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filesystem_data', to='sysmon.partitiondata'),
        ),
    ]
